/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodjassignment;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.table.TableRowSorter;
import javax.swing.table.TableModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
/**
 *
 * @author user
 */
public class AdminSearchUserPage extends javax.swing.JFrame {
   
    
    /**
     * Creates new form AdminSearchUserPage
     */
    Users admin = new Users();
    public AdminSearchUserPage(String adminID) {
        initComponents();
        this.setLocationRelativeTo(null);
        admin.setUserID(adminID);
        ((DefaultTableModel)tblUser.getModel()).setNumRows(0);
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tblUser.getModel());
        DefaultTableModel model =(DefaultTableModel)tblUser.getModel();
        tblUser.setRowSorter(rowSorter);
        Users user = new Users();
        String [] userArray = user.userViewAll();
        model.setColumnIdentifiers(userArray[0].split("\\|"));
        model.setColumnCount(11);
        for (int i =0; i < userArray.length ; i ++)
        {
            if(i > 1 && !userArray[i].startsWith("Admin"))
            {
                
              String temp = userArray[i];
              
              String [] temp2 = temp.split("\\|");  
              model.addRow(temp2);  
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbTypeofUser = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnModify = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        lblTitle.setBackground(new java.awt.Color(102, 102, 102));
        lblTitle.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Search");
        jPanel1.add(lblTitle);
        lblTitle.setBounds(590, 20, 230, 37);

        lblTitle1.setBackground(new java.awt.Color(102, 102, 102));
        lblTitle1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("User");
        jPanel1.add(lblTitle1);
        lblTitle1.setBounds(590, 60, 230, 33);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Citizen or Non Citizen:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(18, 114, 150, 19);

        cbTypeofUser.setBackground(new java.awt.Color(102, 102, 102));
        cbTypeofUser.setEditable(true);
        cbTypeofUser.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        cbTypeofUser.setForeground(new java.awt.Color(255, 255, 255));
        cbTypeofUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Citizen", "Non-Citizen" }));
        cbTypeofUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbTypeofUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbTypeofUserMouseReleased(evt);
            }
        });
        cbTypeofUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTypeofUserActionPerformed(evt);
            }
        });
        jPanel1.add(cbTypeofUser);
        cbTypeofUser.setBounds(170, 110, 110, 21);

        txtSearch.setBackground(new java.awt.Color(102, 102, 102));
        txtSearch.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.setBorder(null);
        txtSearch.setCaretColor(new java.awt.Color(255, 255, 255));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearch);
        txtSearch.setBounds(90, 310, 170, 20);

        btnModify.setBackground(new java.awt.Color(102, 102, 102));
        btnModify.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        btnModify.setForeground(new java.awt.Color(255, 255, 255));
        btnModify.setText("Modify");
        btnModify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        jPanel1.add(btnModify);
        btnModify.setBounds(310, 310, 110, 30);

        tblUser.setBackground(new java.awt.Color(102, 102, 102));
        tblUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblUser.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        tblUser.setForeground(new java.awt.Color(255, 255, 255));
        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane3.setViewportView(tblUser);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(10, 150, 1396, 145);

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search here: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 310, 80, 19);

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back to Previous Page");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(1160, 390, 220, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("—————————————————");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 320, 450, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1429, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        DefaultTableModel model =(DefaultTableModel)tblUser.getModel();
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tblUser.getModel());
        tblUser.setRowSorter(rowSorter);
        rowSorter.setRowFilter(RowFilter.regexFilter(txtSearch.getText().trim()));
    }//GEN-LAST:event_txtSearchKeyReleased

    private void cbTypeofUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTypeofUserActionPerformed
        ((DefaultTableModel)tblUser.getModel()).setNumRows(0);
        Users user = new Users();
        String choice = cbTypeofUser.getSelectedItem().toString().trim();
        DefaultTableModel model =(DefaultTableModel)tblUser.getModel();
        String [] userArray = user.userViewAll();
        model.setColumnIdentifiers(userArray[0].split("\\|"));
        
        for (int i =0; i < userArray.length ; i ++)
        {
            
            if(i > 1 & !userArray[i].startsWith("Admin"))
            {
              
              String temp = userArray[i];
              String [] temp2 = temp.split("\\|");
              if(choice.equals("All")){
                  model.addRow(temp2);  
              }else if (choice.equals("Citizen") && temp2[9].equals("Malaysia"))
              {
                model.addRow(temp2); 
              }else if (choice.equals("Non-Citizen") && (!"Malaysia".equals(temp2[9].trim())) && temp2[9].trim().length() != 0)
              {
                  model.addRow(temp2); 
              }

            }
        }
    }//GEN-LAST:event_cbTypeofUserActionPerformed

    private void cbTypeofUserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTypeofUserMouseReleased
        
    }//GEN-LAST:event_cbTypeofUserMouseReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       setVisible(false);
       dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        DefaultTableModel model = (DefaultTableModel)tblUser.getModel();
        if(tblUser.getSelectionModel().isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(null, "please selected properly");
        }else
        {
            int nRow =tblUser.getSelectedRow();
            int col = 11;
            String [][] tb = new String[1][11];

            for(int i = 0; i < col; i ++)
            {
                tb[0][i] = model.getValueAt(nRow, i).toString();

            }
            
            
            Users user = new Users(tb[0][0],tb[0][1],tb[0][2],tb[0][3],tb[0][4],tb[0][5],tb[0][6],tb[0][7],tb[0][8],tb[0][9],tb[0][10]);
            AdminModifyUserAccountPage ASUP = new AdminModifyUserAccountPage(user,admin.getUserID());
            ASUP.setVisible(true);
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed
                 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSearchUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSearchUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSearchUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSearchUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSearchUserPage("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnModify;
    private javax.swing.JComboBox<String> cbTypeofUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
