/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodjassignment;

import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author User
 */
public class AdminModifyTrackingPage extends javax.swing.JFrame {

    public void showsAppointTracking()
    {
         ((DefaultTableModel)tblAppointModifyTracking.getModel()).setNumRows(0);
        DefaultTableModel model =(DefaultTableModel)tblAppointModifyTracking.getModel();
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tblAppointModifyTracking.getModel());
        tblAppointModifyTracking.setRowSorter(rowSorter);
        AModifyAppointmentTracking MTrack = new AModifyAppointmentTracking();
        
        String[] Heading = new String[]{"Tracking ID","Admin ID","Appointment ID","Action","Target Data","Date","Time","Remark"};
        model.setColumnIdentifiers(Heading);
        model.setColumnCount(8);
        ArrayList<AModifyAppointmentTracking> MTrackArr = new ArrayList<>();
        MTrackArr = MTrack.FileRead();
        for(int i = 0 ; i < MTrackArr.size(); i ++)
        {
            String[] temp = MTrackArr.get(i).toString().split("\\|");
            model.addRow(temp);
        }
        
    }
    
    public void showsVCenterTracking()
    {
         ((DefaultTableModel)tblAppointModifyTracking.getModel()).setNumRows(0);
        DefaultTableModel model =(DefaultTableModel)tblAppointModifyTracking.getModel();
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tblAppointModifyTracking.getModel());
        tblAppointModifyTracking.setRowSorter(rowSorter);
        AModifyVaccinesTracking MTrack = new AModifyVaccinesTracking();
        
        String[] Heading = new String[]{"Tracking ID","Admin ID","VCenter ID","Action","Target Data","Date","Time","Remark"};
        model.setColumnIdentifiers(Heading);
        model.setColumnCount(8);
        ArrayList<AModifyVaccinesTracking> MTrackArr = new ArrayList<>();
        MTrackArr = MTrack.FileRead();
        for(int i = 0 ; i < MTrackArr.size(); i ++)
        {
            String[] temp = MTrackArr.get(i).toString().split("\\|");
            model.addRow(temp);
        }
        
    }
    
    public void showsUserModifyTracking()
    {
        ((DefaultTableModel)tblAppointModifyTracking.getModel()).setNumRows(0);
        DefaultTableModel model =(DefaultTableModel)tblAppointModifyTracking.getModel();
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tblAppointModifyTracking.getModel());
        tblAppointModifyTracking.setRowSorter(rowSorter);
        AModifyUserTracking MTrack = new AModifyUserTracking();
        
        String[] Heading = new String[]{"Tracking ID","Admin ID","User ID","Action","Target Data","Date","Time","Remark"};
        model.setColumnIdentifiers(Heading);
        model.setColumnCount(8);
        ArrayList<AModifyUserTracking> MTrackArr = new ArrayList<>();
        MTrackArr = MTrack.FileRead();
        for(int i = 0 ; i < MTrackArr.size(); i ++)
        {
            String[] temp = MTrackArr.get(i).toString().split("\\|");
            model.addRow(temp);
        }
    }
    
    Users admin = new Users();
    public AdminModifyTrackingPage(String adminID) {
        initComponents();
        this.setLocationRelativeTo(null);
        admin.setUserID(adminID);
//        showsAppointTracking();
        showsVCenterTracking();
//          showsUserModifyTracking();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAppointModifyTracking = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnVaccine = new javax.swing.JButton();
        btnApp = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblAppointModifyTracking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAppointModifyTracking);

        btnBack.setText("Back to Main Menu");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnVaccine.setText("VCenter");
        btnVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaccineActionPerformed(evt);
            }
        });

        btnApp.setText("Appointment");
        btnApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppActionPerformed(evt);
            }
        });

        btnUser.setText("User");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        jLabel1.setText("Track Modify:");

        jLabel2.setText("Search Here:");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnVaccine)
                        .addGap(18, 18, 18)
                        .addComponent(btnApp)
                        .addGap(18, 18, 18)
                        .addComponent(btnUser))
                    .addComponent(btnBack)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVaccine)
                    .addComponent(btnApp)
                    .addComponent(btnUser))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminMainPage AMP = new AdminMainPage(admin.getUserID());
        AMP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaccineActionPerformed
        this.showsVCenterTracking();
    }//GEN-LAST:event_btnVaccineActionPerformed

    private void btnAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppActionPerformed
        this.showsAppointTracking();
    }//GEN-LAST:event_btnAppActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        this.showsUserModifyTracking();
    }//GEN-LAST:event_btnUserActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        DefaultTableModel model =(DefaultTableModel)tblAppointModifyTracking.getModel();
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tblAppointModifyTracking.getModel());
        tblAppointModifyTracking.setRowSorter(rowSorter);
        rowSorter.setRowFilter(RowFilter.regexFilter(txtSearch.getText().trim()));
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminModifyTrackingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminModifyTrackingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminModifyTrackingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminModifyTrackingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminModifyTrackingPage("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApp;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUser;
    private javax.swing.JButton btnVaccine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAppointModifyTracking;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
