/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodjassignment;

import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class UserAppointmentViewPage extends javax.swing.JFrame {

    /**
     * Creates new form UserAppointmentViewPage
     */
    
    private String userID;
    private File file = new File("Appointment.txt");
    private CurrentDateTime currentDateTime = new CurrentDateTime();
    public UserAppointmentViewPage(String userID) 
    {
        initComponents();
        this.setLocationRelativeTo(null);
        this.userID = userID;
        Appointment appointment = new Appointment();
        if (appointment.viewAppointment(userID))
        {
            lblAppointmentID.setText(appointment.getAptID());
            lblCenterID.setText(appointment.getCenterID());
            lblState.setText(appointment.getAddress());
            lblDate.setText(appointment.getDate());
            lblTime.setText(appointment.getTime());
            lblStatus.setText(appointment.getAptStatus());
            lblVaccineType.setText(appointment.getVacType());
            lblDose.setText(appointment.getAptID());
            if ("Cancelled".equals(appointment.getAptStatus()) || 
                    "Request Cancellation".equals(appointment.getAptStatus()))
            {
                btnCancel.setVisible(false);
            }
        }
        else
        {
            btnCancel.setVisible(false);
            lblAppointmentID.setText("NULL");
            lblCenterID.setText("NULL");
            lblState.setText("NULL");
            lblDate.setText("NULL");
            lblTime.setText("NULL");
            lblStatus.setText("NULL");
            lblVaccineType.setText("NULL");
            lblDose.setText("NULL");
        }
        
        lblCurrentTime.setText("<html>" + currentDateTime.currentDate() + " <br> " +
                currentDateTime.currentWeek() + "<br>" +
                currentDateTime.currentTime() + "<html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblAppointmentID = new javax.swing.JLabel();
        lblCenterID = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblVaccineType = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblAdminName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAdminName1 = new javax.swing.JLabel();
        lblDose = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblCurrentTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        lblTime.setBackground(new java.awt.Color(102, 102, 102));
        lblTime.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("jLabel9");
        lblTime.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblTime.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblTime);
        lblTime.setBounds(150, 206, 148, 23);

        lblAppointmentID.setBackground(new java.awt.Color(102, 102, 102));
        lblAppointmentID.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        lblAppointmentID.setForeground(new java.awt.Color(255, 255, 255));
        lblAppointmentID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppointmentID.setText("jLabel9");
        lblAppointmentID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblAppointmentID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblAppointmentID);
        lblAppointmentID.setBounds(150, 102, 148, 23);

        lblCenterID.setBackground(new java.awt.Color(102, 102, 102));
        lblCenterID.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        lblCenterID.setForeground(new java.awt.Color(255, 255, 255));
        lblCenterID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCenterID.setText("jLabel9");
        lblCenterID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblCenterID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblCenterID);
        lblCenterID.setBounds(150, 128, 148, 23);

        lblDate.setBackground(new java.awt.Color(102, 102, 102));
        lblDate.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setText("jLabel9");
        lblDate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblDate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblDate);
        lblDate.setBounds(150, 180, 148, 23);

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Vaccine Type:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(53, 261, 80, 17);

        lblState.setBackground(new java.awt.Color(102, 102, 102));
        lblState.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        lblState.setForeground(new java.awt.Color(255, 255, 255));
        lblState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblState.setText("jLabel9");
        lblState.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblState.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblState);
        lblState.setBounds(150, 154, 148, 23);

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Appoint Status:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(49, 235, 90, 17);

        lblStatus.setBackground(new java.awt.Color(102, 102, 102));
        lblStatus.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("jLabel9");
        lblStatus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblStatus);
        lblStatus.setBounds(150, 232, 148, 23);

        lblVaccineType.setBackground(new java.awt.Color(102, 102, 102));
        lblVaccineType.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        lblVaccineType.setForeground(new java.awt.Color(255, 255, 255));
        lblVaccineType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVaccineType.setText("jLabel9");
        lblVaccineType.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblVaccineType.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblVaccineType);
        lblVaccineType.setBounds(150, 258, 148, 23);

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Time:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(99, 209, 30, 17);

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(99, 183, 30, 17);

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Dose:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(96, 286, 40, 17);

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Appointment ID:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(36, 105, 100, 17);

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("State:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(98, 157, 30, 17);

        lblAdminName.setBackground(new java.awt.Color(102, 102, 102));
        lblAdminName.setFont(new java.awt.Font("Tempus Sans ITC", 0, 32)); // NOI18N
        lblAdminName.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminName.setText("Your");
        jPanel1.add(lblAdminName);
        lblAdminName.setBounds(140, 20, 70, 42);

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Center ID:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(69, 131, 60, 17);

        lblAdminName1.setBackground(new java.awt.Color(102, 102, 102));
        lblAdminName1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 32)); // NOI18N
        lblAdminName1.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminName1.setText("Appointment");
        jPanel1.add(lblAdminName1);
        lblAdminName1.setBounds(70, 50, 210, 42);

        lblDose.setBackground(new java.awt.Color(102, 102, 102));
        lblDose.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        lblDose.setForeground(new java.awt.Color(255, 255, 255));
        lblDose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDose.setText("jLabel9");
        lblDose.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblDose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblDose);
        lblDose.setBounds(150, 284, 148, 18);

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(260, 410, 100, 30);

        btnCancel.setBackground(new java.awt.Color(102, 102, 102));
        btnCancel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel Appointment");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);
        btnCancel.setBounds(109, 320, 160, 40);

        lblCurrentTime.setBackground(new java.awt.Color(102, 102, 102));
        lblCurrentTime.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        lblCurrentTime.setForeground(new java.awt.Color(255, 255, 255));
        lblCurrentTime.setText("jLabel1");
        jPanel1.add(lblCurrentTime);
        lblCurrentTime.setBounds(320, 0, 60, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        UserAppointmentMainPage userAppointmentMainPage = new UserAppointmentMainPage(this.userID);
        userAppointmentMainPage.setVisible(true);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        Appointment appointment = new Appointment();
        int n = JOptionPane.showOptionDialog(null, "Are you sure you want to cancel the appointment?", "Check",
                JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE,null,null,null);
        if (appointment.viewAppointment(this.userID))
        {
            if ("Requesting".equals(appointment.getAptStatus())) //if requesting, cancel directly
            {
                appointment.setAptStatus("Cancelled");
                switch (n)
                {
                    case 0:
                        appointment.appointmentModify();
                        JOptionPane.showMessageDialog(null, "Your appointment has been cancelled!");
                        break;
                    case 1:
                        break;
                }
            }
            else if ("Approved".equals(appointment.getAptStatus())) //if approved, send request to admin
            {
                appointment.setAptStatus("Request Cancellation");
                switch (n)
                {
                    case 0:
                        appointment.appointmentModify();
                        JOptionPane.showMessageDialog(null, "<html> Your cancellation request has been sent to the administrator!"
                                + " <br> You can't book any appointments until approved by the administrator!","Confirmation",
                                JOptionPane.WARNING_MESSAGE);
                        break;
                    case 1:
                        break;
                }   
            }
        }
        this.setVisible(false);
        this.dispose();
        UserAppointmentMainPage userAppointmentMainPage = new UserAppointmentMainPage(this.userID);
        userAppointmentMainPage.setVisible(true);
        
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAppointmentViewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAppointmentViewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAppointmentViewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAppointmentViewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAppointmentViewPage("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdminName;
    private javax.swing.JLabel lblAdminName1;
    private javax.swing.JLabel lblAppointmentID;
    private javax.swing.JLabel lblCenterID;
    private javax.swing.JLabel lblCurrentTime;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDose;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblVaccineType;
    // End of variables declaration//GEN-END:variables
}
