/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodjassignment;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class UserMainPage extends javax.swing.JFrame 
{
    private String userID;
    private Users user = new Users();
    private Appointment appointment = new Appointment();
    private CurrentDateTime currentDateTime = new CurrentDateTime();
    public UserMainPage(String userID) 
    {
        initComponents();
        this.setLocationRelativeTo(null);
        dlgDoseStatus.setLocationRelativeTo(null);
        this.userID = userID;
        this.userID = userID;
        Appointment appointment = new Appointment();
        user.userProfile(this.userID);
        lblTitle.setText(user.getName());
        lblVacStatus.setText("<html><b><u>Vaccination Status</u><b><html>");
        lblTime.setText("<html>" + currentDateTime.currentDate() + " <br> " +
                currentDateTime.currentWeek() + "<br>" +
                currentDateTime.currentTime() + "<html>");
        
        //Dialog disign
        lblUsernameDG.setText(user.getName());
        lblIC.setText(user.getIC());

        appointment.digitalCertificate(this.userID,"FirstDose");
        lblDate1.setText(appointment.getDate());
        lblCenterID1.setText(appointment.getCenterID());
        lblVaccineID1.setText(appointment.getVacID());
        lblVaccineType1.setText(appointment.getVacType());
        ////////////////////////////////////////////////////////
        appointment.digitalCertificate(this.userID,"SecondDose");
        lblDate2.setText(appointment.getDate());
        lblCenterID2.setText(appointment.getCenterID());
        lblVaccineID2.setText(appointment.getVacID());
        lblVaccineType2.setText(appointment.getVacType());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgDoseStatus = new javax.swing.JDialog();
        plDoseStatus = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        lblTITLE = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblIC = new javax.swing.JLabel();
        lblUsernameDG = new javax.swing.JLabel();
        plDose1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblVaccineID1 = new javax.swing.JLabel();
        lblDate1 = new javax.swing.JLabel();
        lblCenterID1 = new javax.swing.JLabel();
        lblVaccineType1 = new javax.swing.JLabel();
        plDose2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblVaccineID2 = new javax.swing.JLabel();
        lblDate2 = new javax.swing.JLabel();
        lblCenterID2 = new javax.swing.JLabel();
        lblVaccineType2 = new javax.swing.JLabel();
        plUserMain = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnProfile = new javax.swing.JButton();
        btnAppointment = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnModify = new javax.swing.JButton();
        lblVacStatus = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        dlgDoseStatus.setMinimumSize(new java.awt.Dimension(665, 580));

        plDoseStatus.setBackground(new java.awt.Color(255, 204, 102));
        plDoseStatus.setLayout(null);

        lblTitle2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("Digital Certificate");
        plDoseStatus.add(lblTitle2);
        lblTitle2.setBounds(180, 80, 220, 40);

        lblTITLE.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        lblTITLE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTITLE.setText("Covid-19 Vaccination");
        plDoseStatus.add(lblTITLE);
        lblTITLE.setBounds(110, 30, 370, 50);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("—————————————————————————————————————————————");
        plDoseStatus.add(jLabel3);
        jLabel3.setBounds(10, 120, 570, 15);

        lblIC.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        lblIC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIC.setText("IC");
        plDoseStatus.add(lblIC);
        lblIC.setBounds(30, 180, 520, 33);

        lblUsernameDG.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        lblUsernameDG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsernameDG.setText("UserName");
        plDoseStatus.add(lblUsernameDG);
        lblUsernameDG.setBounds(10, 140, 560, 48);

        plDose1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel7.setText("Dose 1:");

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel9.setText("Date:");

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel10.setText("CenterID:");

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel11.setText("Vaccine Type:");

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel12.setText("Vaccine ID:");

        lblVaccineID1.setBackground(new java.awt.Color(255, 255, 255));
        lblVaccineID1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        lblVaccineID1.setText("                                      ");

        lblDate1.setBackground(new java.awt.Color(255, 255, 255));
        lblDate1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        lblDate1.setText("                                      ");

        lblCenterID1.setBackground(new java.awt.Color(255, 255, 255));
        lblCenterID1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        lblCenterID1.setText("                                      ");

        lblVaccineType1.setBackground(new java.awt.Color(255, 255, 255));
        lblVaccineType1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        lblVaccineType1.setText("                                  ");

        javax.swing.GroupLayout plDose1Layout = new javax.swing.GroupLayout(plDose1);
        plDose1.setLayout(plDose1Layout);
        plDose1Layout.setHorizontalGroup(
            plDose1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plDose1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plDose1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addGroup(plDose1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(plDose1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jLabel7))
                        .addComponent(jLabel11))
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(plDose1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCenterID1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVaccineType1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVaccineID1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        plDose1Layout.setVerticalGroup(
            plDose1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plDose1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plDose1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lblDate1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plDose1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblCenterID1))
                .addGap(11, 11, 11)
                .addGroup(plDose1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblVaccineID1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plDose1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblVaccineType1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        plDoseStatus.add(plDose1);
        plDose1.setBounds(40, 220, 500, 149);

        plDose2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel8.setText("Dose 2:");

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel13.setText("Date:");

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel14.setText("CenterID:");

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel15.setText("Vaccine Type:");

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel16.setText("Vaccine ID:");

        lblVaccineID2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        lblVaccineID2.setText("                                            ");

        lblDate2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        lblDate2.setText("                                     ");

        lblCenterID2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        lblCenterID2.setText("                                           ");

        lblVaccineType2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        lblVaccineType2.setText("                                             ");

        javax.swing.GroupLayout plDose2Layout = new javax.swing.GroupLayout(plDose2);
        plDose2.setLayout(plDose2Layout);
        plDose2Layout.setHorizontalGroup(
            plDose2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plDose2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plDose2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plDose2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(plDose2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15))
                        .addComponent(jLabel13))
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(plDose2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCenterID2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVaccineType2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVaccineID2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        plDose2Layout.setVerticalGroup(
            plDose2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plDose2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plDose2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plDose2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblCenterID2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plDose2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblVaccineID2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plDose2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblVaccineType2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        plDoseStatus.add(plDose2);
        plDose2.setBounds(40, 380, 500, 144);

        javax.swing.GroupLayout dlgDoseStatusLayout = new javax.swing.GroupLayout(dlgDoseStatus.getContentPane());
        dlgDoseStatus.getContentPane().setLayout(dlgDoseStatusLayout);
        dlgDoseStatusLayout.setHorizontalGroup(
            dlgDoseStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plDoseStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );
        dlgDoseStatusLayout.setVerticalGroup(
            dlgDoseStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plDoseStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        plUserMain.setBackground(new java.awt.Color(102, 102, 102));
        plUserMain.setLayout(null);

        lblTitle1.setBackground(new java.awt.Color(102, 102, 102));
        lblTitle1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Welcome Back");
        plUserMain.add(lblTitle1);
        lblTitle1.setBounds(50, 40, 260, 50);

        lblTitle.setBackground(new java.awt.Color(102, 102, 102));
        lblTitle.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("User Name");
        plUserMain.add(lblTitle);
        lblTitle.setBounds(30, 70, 300, 50);

        btnProfile.setBackground(new java.awt.Color(102, 102, 102));
        btnProfile.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setText("Profile");
        btnProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        plUserMain.add(btnProfile);
        btnProfile.setBounds(110, 128, 130, 50);

        btnAppointment.setBackground(new java.awt.Color(102, 102, 102));
        btnAppointment.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        btnAppointment.setForeground(new java.awt.Color(255, 255, 255));
        btnAppointment.setText("Appointment");
        btnAppointment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointmentActionPerformed(evt);
            }
        });
        plUserMain.add(btnAppointment);
        btnAppointment.setBounds(110, 290, 130, 50);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View Profile");
        plUserMain.add(jLabel1);
        jLabel1.setBounds(210, 180, 69, 14);

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("View Appointment");
        plUserMain.add(jLabel2);
        jLabel2.setBounds(210, 340, 100, 15);

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ModifyProfile");
        plUserMain.add(jLabel4);
        jLabel4.setBounds(210, 260, 69, 15);

        btnModify.setBackground(new java.awt.Color(102, 102, 102));
        btnModify.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        btnModify.setForeground(new java.awt.Color(255, 255, 255));
        btnModify.setText("Modify");
        btnModify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        plUserMain.add(btnModify);
        btnModify.setBounds(110, 210, 130, 48);

        lblVacStatus.setBackground(new java.awt.Color(102, 102, 102));
        lblVacStatus.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        lblVacStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblVacStatus.setText("Vaccination Status:");
        lblVacStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVacStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVacStatusMouseClicked(evt);
            }
        });
        plUserMain.add(lblVacStatus);
        lblVacStatus.setBounds(10, 380, 130, 17);

        lblTime.setBackground(new java.awt.Color(102, 102, 102));
        lblTime.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("jLabel5");
        plUserMain.add(lblTime);
        lblTime.setBounds(320, 0, 60, 70);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        plUserMain.add(jButton1);
        jButton1.setBounds(250, 410, 110, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plUserMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plUserMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        UserProfilePage userProfilePage = new UserProfilePage(this.userID);
        this.setVisible(false);
        userProfilePage.setVisible(true);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
        Validation validation = new Validation();
        if (validation.validationUserModify(this.userID))
        {
            UserModifyProfilePage userModifyProfilePage = new UserModifyProfilePage(this.userID);
            this.setVisible(false);
            this.dispose();
            userModifyProfilePage.setVisible(true);
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentActionPerformed
        // TODO add your handling code here:
        user.userProfile(this.userID);
        appointment.firstDoseDone(userID);
        if ("SecondDose".equals(user.getVacStatus()) && AppStatus.Done.toString().equals(appointment.getAptStatus()))
        {
            JOptionPane.showMessageDialog(null, "<html> Congratulation! You have been vaccinated!"
                    + " <br> No appointment required! <html>");
        }
        else
        {
            UserAppointmentMainPage userAppointment = new UserAppointmentMainPage(this.userID);
            this.setVisible(false);
            userAppointment.setVisible(true);
        }
    }//GEN-LAST:event_btnAppointmentActionPerformed

    private void lblVacStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVacStatusMouseClicked
        // TODO add your handling code here:
        lblVacStatus.addMouseListener(new MouseAdapter()  
        {  
            public void mouseClicked(MouseEvent e)  
            {  
                dlgDoseStatus.setVisible(true);
            }  
        }); 
    }//GEN-LAST:event_lblVacStatusMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMainPage("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointment;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnProfile;
    private javax.swing.JDialog dlgDoseStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCenterID1;
    private javax.swing.JLabel lblCenterID2;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblDate2;
    private javax.swing.JLabel lblIC;
    private javax.swing.JLabel lblTITLE;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblUsernameDG;
    private javax.swing.JLabel lblVacStatus;
    private javax.swing.JLabel lblVaccineID1;
    private javax.swing.JLabel lblVaccineID2;
    private javax.swing.JLabel lblVaccineType1;
    private javax.swing.JLabel lblVaccineType2;
    private javax.swing.JPanel plDose1;
    private javax.swing.JPanel plDose2;
    private javax.swing.JPanel plDoseStatus;
    private javax.swing.JPanel plUserMain;
    // End of variables declaration//GEN-END:variables
}
